name: drunken-tyrion-staging
registries:
ships:
    local: {ip: localhost, docker_port: 2375}
services:
  #proxy:
    #image: gregory90/nginx-my:latest
    #instances:
      #proxy-1:
        #ship: local 
        #ports: 
            #proxy:
                #exposed: 80
                #external: 80
        #lifecycle:
          #running: [{type: tcp, port: proxy}]
        #cmd: /sbin/my_init

  app:
    image: gregory90/nodejs-my:latest
    instances:
      app-staging-1:
        ship: local 
        ports: 
            node:
                exposed: 3000
                external: [127.0.0.1, 3001]
        lifecycle:
          running: [{type: tcp, port: node}]
        env:
            MONGODB_HOST: db-staging-1.mongodb.dev.docker
            MONGODB_PORT: 27018
            EXPRESS_PORT: 3001
            NODE_ENV: production 
        cmd: /sbin/my_init

  db:
    image: gregory90/mongodb:latest
    instances:
      db-staging-1:
        ship: local 
        ports: 
            db:
                exposed: 27017
                external: [127.0.0.1, 27018]
        lifecycle:
          running: [{type: tcp, port: db}]
        volumes:
            /data/db: /data/drunken-tyrion/staging/mongodb
        cmd: /sbin/my_init

  redis:
    image: gregory90/redis:latest
    instances:
      redis-staging-1:
        ship: local 
        ports: 
            redis:
                exposed: 6379
                external: [127.0.0.1, 6380]
        lifecycle:
          running: [{type: tcp, port: redis}]
        volumes:
            /data: /data/drunken-tyrion/staging/redis
        cmd: /sbin/my_init
